import 'dart:async';
import 'dart:convert';
import 'dart:developer' as developer;
import 'dart:io';
import 'dart:ui' as ui;

import 'package:background_downloader/background_downloader.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter/material.dart';
import 'package:just_audio/just_audio.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:geocoding/geocoding.dart';
import 'package:geolocator/geolocator.dart';
import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart' as tz;
import 'package:url_launcher/url_launcher.dart';

part 'core/quran_data.dart';
part 'core/appearance.dart';
part 'core/diagnostics.dart';
part 'services/audio_service.dart';
part 'services/prayer_service.dart';
part 'services/download_service.dart';
part 'services/tajwid_service.dart';
part 'services/juz_catalog.dart';
part 'services/location_service.dart';
part 'widgets/error_details.dart';
part 'widgets/appearance_card.dart';
part 'widgets/tajwid_panel.dart';
part 'screens/app_shell.dart';
part 'screens/reader_screen.dart';
part 'screens/diagnostics_screen.dart';
part 'screens/downloads_screen.dart';
part 'screens/search_screen.dart';
part 'screens/prayer_settings_screen.dart';
